// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api/v1/me.proto

/*
Package api_v1 is a generated protocol buffer package.

It is generated from these files:
	proto/api/v1/me.proto

It has these top-level messages:
	GetMeRequest
	NotificationTimeSpan
	GetMeResponse
	GetMeEmailRequest
	GetMeEmailResponse
	UpdateMeEmailRequest
	UpdateMeEmailResponse
	UpdateMeNotificationTimeSpanRequest
	UpdateMeNotificationTimeSpanResponse
*/
package api_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMeRequest struct {
}

func (m *GetMeRequest) Reset()                    { *m = GetMeRequest{} }
func (m *GetMeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMeRequest) ProtoMessage()               {}
func (*GetMeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NotificationTimeSpan struct {
	FromHour   int32 `protobuf:"varint,1,opt,name=fromHour" json:"fromHour,omitempty"`
	FromMinute int32 `protobuf:"varint,2,opt,name=fromMinute" json:"fromMinute,omitempty"`
	ToHour     int32 `protobuf:"varint,3,opt,name=toHour" json:"toHour,omitempty"`
	ToMinute   int32 `protobuf:"varint,4,opt,name=toMinute" json:"toMinute,omitempty"`
}

func (m *NotificationTimeSpan) Reset()                    { *m = NotificationTimeSpan{} }
func (m *NotificationTimeSpan) String() string            { return proto.CompactTextString(m) }
func (*NotificationTimeSpan) ProtoMessage()               {}
func (*NotificationTimeSpan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NotificationTimeSpan) GetFromHour() int32 {
	if m != nil {
		return m.FromHour
	}
	return 0
}

func (m *NotificationTimeSpan) GetFromMinute() int32 {
	if m != nil {
		return m.FromMinute
	}
	return 0
}

func (m *NotificationTimeSpan) GetToHour() int32 {
	if m != nil {
		return m.ToHour
	}
	return 0
}

func (m *NotificationTimeSpan) GetToMinute() int32 {
	if m != nil {
		return m.ToMinute
	}
	return 0
}

type GetMeResponse struct {
	UserId                int32                   `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Email                 string                  `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	NotificationTimeSpans []*NotificationTimeSpan `protobuf:"bytes,3,rep,name=notificationTimeSpans" json:"notificationTimeSpans,omitempty"`
}

func (m *GetMeResponse) Reset()                    { *m = GetMeResponse{} }
func (m *GetMeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMeResponse) ProtoMessage()               {}
func (*GetMeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetMeResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetMeResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetMeResponse) GetNotificationTimeSpans() []*NotificationTimeSpan {
	if m != nil {
		return m.NotificationTimeSpans
	}
	return nil
}

type GetMeEmailRequest struct {
}

func (m *GetMeEmailRequest) Reset()                    { *m = GetMeEmailRequest{} }
func (m *GetMeEmailRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMeEmailRequest) ProtoMessage()               {}
func (*GetMeEmailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetMeEmailResponse struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *GetMeEmailResponse) Reset()                    { *m = GetMeEmailResponse{} }
func (m *GetMeEmailResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMeEmailResponse) ProtoMessage()               {}
func (*GetMeEmailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetMeEmailResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateMeEmailRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *UpdateMeEmailRequest) Reset()                    { *m = UpdateMeEmailRequest{} }
func (m *UpdateMeEmailRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateMeEmailRequest) ProtoMessage()               {}
func (*UpdateMeEmailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateMeEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateMeEmailResponse struct {
}

func (m *UpdateMeEmailResponse) Reset()                    { *m = UpdateMeEmailResponse{} }
func (m *UpdateMeEmailResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateMeEmailResponse) ProtoMessage()               {}
func (*UpdateMeEmailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type UpdateMeNotificationTimeSpanRequest struct {
	NotificationTimeSpans []*NotificationTimeSpan `protobuf:"bytes,1,rep,name=notificationTimeSpans" json:"notificationTimeSpans,omitempty"`
}

func (m *UpdateMeNotificationTimeSpanRequest) Reset()         { *m = UpdateMeNotificationTimeSpanRequest{} }
func (m *UpdateMeNotificationTimeSpanRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMeNotificationTimeSpanRequest) ProtoMessage()    {}
func (*UpdateMeNotificationTimeSpanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7}
}

func (m *UpdateMeNotificationTimeSpanRequest) GetNotificationTimeSpans() []*NotificationTimeSpan {
	if m != nil {
		return m.NotificationTimeSpans
	}
	return nil
}

type UpdateMeNotificationTimeSpanResponse struct {
}

func (m *UpdateMeNotificationTimeSpanResponse) Reset()         { *m = UpdateMeNotificationTimeSpanResponse{} }
func (m *UpdateMeNotificationTimeSpanResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMeNotificationTimeSpanResponse) ProtoMessage()    {}
func (*UpdateMeNotificationTimeSpanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8}
}

func init() {
	proto.RegisterType((*GetMeRequest)(nil), "api.v1.GetMeRequest")
	proto.RegisterType((*NotificationTimeSpan)(nil), "api.v1.NotificationTimeSpan")
	proto.RegisterType((*GetMeResponse)(nil), "api.v1.GetMeResponse")
	proto.RegisterType((*GetMeEmailRequest)(nil), "api.v1.GetMeEmailRequest")
	proto.RegisterType((*GetMeEmailResponse)(nil), "api.v1.GetMeEmailResponse")
	proto.RegisterType((*UpdateMeEmailRequest)(nil), "api.v1.UpdateMeEmailRequest")
	proto.RegisterType((*UpdateMeEmailResponse)(nil), "api.v1.UpdateMeEmailResponse")
	proto.RegisterType((*UpdateMeNotificationTimeSpanRequest)(nil), "api.v1.UpdateMeNotificationTimeSpanRequest")
	proto.RegisterType((*UpdateMeNotificationTimeSpanResponse)(nil), "api.v1.UpdateMeNotificationTimeSpanResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error)
	GetMeEmail(ctx context.Context, in *GetMeEmailRequest, opts ...grpc.CallOption) (*GetMeEmailResponse, error)
	UpdateMeEmail(ctx context.Context, in *UpdateMeEmailRequest, opts ...grpc.CallOption) (*UpdateMeEmailResponse, error)
	UpdateMeNotificationTimeSpan(ctx context.Context, in *UpdateMeNotificationTimeSpanRequest, opts ...grpc.CallOption) (*UpdateMeNotificationTimeSpanResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error) {
	out := new(GetMeResponse)
	err := grpc.Invoke(ctx, "/api.v1.API/GetMe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetMeEmail(ctx context.Context, in *GetMeEmailRequest, opts ...grpc.CallOption) (*GetMeEmailResponse, error) {
	out := new(GetMeEmailResponse)
	err := grpc.Invoke(ctx, "/api.v1.API/GetMeEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateMeEmail(ctx context.Context, in *UpdateMeEmailRequest, opts ...grpc.CallOption) (*UpdateMeEmailResponse, error) {
	out := new(UpdateMeEmailResponse)
	err := grpc.Invoke(ctx, "/api.v1.API/UpdateMeEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateMeNotificationTimeSpan(ctx context.Context, in *UpdateMeNotificationTimeSpanRequest, opts ...grpc.CallOption) (*UpdateMeNotificationTimeSpanResponse, error) {
	out := new(UpdateMeNotificationTimeSpanResponse)
	err := grpc.Invoke(ctx, "/api.v1.API/UpdateMeNotificationTimeSpan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error)
	GetMeEmail(context.Context, *GetMeEmailRequest) (*GetMeEmailResponse, error)
	UpdateMeEmail(context.Context, *UpdateMeEmailRequest) (*UpdateMeEmailResponse, error)
	UpdateMeNotificationTimeSpan(context.Context, *UpdateMeNotificationTimeSpanRequest) (*UpdateMeNotificationTimeSpanResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.API/GetMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetMeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetMeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.API/GetMeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetMeEmail(ctx, req.(*GetMeEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateMeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMeEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateMeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.API/UpdateMeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateMeEmail(ctx, req.(*UpdateMeEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateMeNotificationTimeSpan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMeNotificationTimeSpanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateMeNotificationTimeSpan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.API/UpdateMeNotificationTimeSpan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateMeNotificationTimeSpan(ctx, req.(*UpdateMeNotificationTimeSpanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMe",
			Handler:    _API_GetMe_Handler,
		},
		{
			MethodName: "GetMeEmail",
			Handler:    _API_GetMeEmail_Handler,
		},
		{
			MethodName: "UpdateMeEmail",
			Handler:    _API_UpdateMeEmail_Handler,
		},
		{
			MethodName: "UpdateMeNotificationTimeSpan",
			Handler:    _API_UpdateMeNotificationTimeSpan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api/v1/me.proto",
}

func init() { proto.RegisterFile("proto/api/v1/me.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0xae, 0xd2, 0x40,
	0x14, 0xcd, 0x50, 0x21, 0x7a, 0x05, 0xa3, 0xd7, 0x56, 0x6b, 0x45, 0x25, 0x23, 0x31, 0xa4, 0x92,
	0x36, 0xe0, 0x8e, 0x9d, 0x0b, 0x23, 0x2c, 0x30, 0xa6, 0xea, 0xd2, 0x45, 0x95, 0x81, 0x4c, 0x42,
	0x3b, 0xb5, 0x9d, 0x92, 0xb8, 0x75, 0xe1, 0xde, 0xf8, 0x0d, 0x7e, 0x88, 0xdf, 0xe0, 0x2f, 0xf8,
	0x21, 0x2f, 0x4c, 0xa7, 0x50, 0x78, 0x85, 0xbc, 0xbc, 0x5d, 0xef, 0x9c, 0x7b, 0xcf, 0x39, 0x73,
	0xe6, 0xa6, 0x60, 0x25, 0xa9, 0x90, 0xc2, 0x0f, 0x13, 0xee, 0x6f, 0x46, 0x7e, 0xc4, 0x3c, 0x55,
	0x63, 0x2b, 0x4c, 0xb8, 0xb7, 0x19, 0x39, 0xdd, 0x95, 0x10, 0xab, 0x35, 0x53, 0x78, 0x18, 0xc7,
	0x42, 0x86, 0x92, 0x8b, 0x38, 0x2b, 0xba, 0xe8, 0x1d, 0x68, 0xbf, 0x65, 0x72, 0xce, 0x02, 0xf6,
	0x2d, 0x67, 0x99, 0xa4, 0x3f, 0x09, 0x98, 0xef, 0x84, 0xe4, 0x4b, 0xfe, 0x55, 0xf5, 0x7d, 0xe4,
	0x11, 0xfb, 0x90, 0x84, 0x31, 0x3a, 0x70, 0x73, 0x99, 0x8a, 0x68, 0x2a, 0xf2, 0xd4, 0x26, 0x3d,
	0x32, 0x68, 0x06, 0xbb, 0x1a, 0x9f, 0x02, 0x6c, 0xbf, 0xe7, 0x3c, 0xce, 0x25, 0xb3, 0x1b, 0x0a,
	0xad, 0x9c, 0xe0, 0x03, 0x68, 0x49, 0xa1, 0x26, 0x0d, 0x85, 0xe9, 0x6a, 0xcb, 0x29, 0x85, 0x9e,
	0xba, 0x51, 0x70, 0x96, 0x35, 0xfd, 0x45, 0xa0, 0xa3, 0x9d, 0x65, 0x89, 0x88, 0x33, 0xc5, 0x92,
	0x67, 0x2c, 0x9d, 0x2d, 0xb4, 0xbe, 0xae, 0xd0, 0x84, 0x26, 0x8b, 0x42, 0xbe, 0x56, 0xc2, 0xb7,
	0x82, 0xa2, 0xc0, 0x00, 0xac, 0xb8, 0xe6, 0x1e, 0x99, 0x6d, 0xf4, 0x8c, 0xc1, 0xed, 0x71, 0xd7,
	0x2b, 0xe2, 0xf1, 0xea, 0x2e, 0x1b, 0xd4, 0x8f, 0xd2, 0xfb, 0x70, 0x4f, 0x59, 0x7a, 0xb3, 0x55,
	0x28, 0x13, 0x73, 0x01, 0xab, 0x87, 0xda, 0xec, 0xce, 0x14, 0xa9, 0x98, 0xa2, 0x43, 0x30, 0x3f,
	0x25, 0x8b, 0x50, 0xb2, 0x43, 0x8e, 0x13, 0xdd, 0x0f, 0xc1, 0x3a, 0xea, 0x2e, 0xc8, 0xe9, 0x77,
	0x78, 0x5e, 0x02, 0xb5, 0xf6, 0x35, 0xeb, 0xc9, 0x08, 0xc8, 0xf5, 0x23, 0x78, 0x01, 0xfd, 0xf3,
	0xd2, 0x85, 0xc5, 0xf1, 0x5f, 0x03, 0x8c, 0xd7, 0xef, 0x67, 0x38, 0x85, 0xa6, 0x4a, 0x07, 0xcd,
	0x52, 0xad, 0xba, 0x6e, 0x8e, 0x75, 0x74, 0xaa, 0x2f, 0x88, 0x3f, 0xfe, 0xfd, 0xff, 0xdd, 0x68,
	0x23, 0xec, 0xb7, 0x1a, 0x3f, 0x03, 0xec, 0x73, 0xc6, 0x47, 0x07, 0x83, 0xd5, 0x30, 0x1d, 0xa7,
	0x0e, 0xd2, 0xc4, 0xb6, 0x22, 0x46, 0xbc, 0xbb, 0x27, 0xf6, 0x8b, 0x7d, 0xe1, 0xd0, 0x39, 0x08,
	0x1b, 0x77, 0xf1, 0xd4, 0xbd, 0x98, 0xf3, 0xe4, 0x04, 0xaa, 0x75, 0x1e, 0x2b, 0x1d, 0x8b, 0x5e,
	0xd2, 0x99, 0x10, 0x17, 0xff, 0x10, 0xe8, 0x9e, 0x0b, 0x11, 0x5f, 0x1e, 0x93, 0x9f, 0x79, 0x65,
	0x67, 0x78, 0xb5, 0x66, 0x6d, 0xcc, 0x55, 0xc6, 0xfa, 0xf4, 0x59, 0xc5, 0x58, 0xdd, 0x4b, 0x4f,
	0x88, 0xfb, 0xa5, 0xa5, 0x7e, 0x11, 0xaf, 0x2e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xef, 0x86, 0x5d,
	0x66, 0x61, 0x04, 0x00, 0x00,
}
