// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Empty struct {
	ID string `json:"id"`
}

type FollowingTeacher struct {
	ID        string   `json:"id"`
	Teacher   *Teacher `json:"teacher"`
	CreatedAt string   `json:"createdAt"`
}

type NotificationTimeSpan struct {
	FromHour   int `json:"fromHour"`
	FromMinute int `json:"fromMinute"`
	ToHour     int `json:"toHour"`
	ToMinute   int `json:"toMinute"`
}

type Teacher struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateViewerInput struct {
	Email *string `json:"email"`
}
