version: "3.3"
services:
  mysql:
    image: "mysql/mysql-server:8.0"
    command: "--secure-file-priv=NULL --default-authentication-plugin=mysql_native_password"
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: "lekcije"
      MYSQL_USER: "lekcije"
      MYSQL_PASSWORD: "lekcije"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./volume/mysql/etc/mysql:/etc/mysql"
#      - "./volume/mysql/var/lib/mysql:/var/lib/mysql"
#      - ./log/mysql:/var/log/mysql
  jaeger:
    image: "jaegertracing/all-in-one:1.48"
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

