// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model2

var TableNames = struct {
	EventLogEmail                  string
	FlashMessage                   string
	FollowingTeacher               string
	Lesson                         string
	LessonStatusLog                string
	MCountry                       string
	MPlan                          string
	NotificationTimeSpan           string
	StatDailyNotificationEvent     string
	StatDailyUserNotificationEvent string
	StatNewLessonNotifier          string
	StatNotifier                   string
	Teacher                        string
	User                           string
	UserAPIToken                   string
	UserGoogle                     string
}{
	EventLogEmail:                  "event_log_email",
	FlashMessage:                   "flash_message",
	FollowingTeacher:               "following_teacher",
	Lesson:                         "lesson",
	LessonStatusLog:                "lesson_status_log",
	MCountry:                       "m_country",
	MPlan:                          "m_plan",
	NotificationTimeSpan:           "notification_time_span",
	StatDailyNotificationEvent:     "stat_daily_notification_event",
	StatDailyUserNotificationEvent: "stat_daily_user_notification_event",
	StatNewLessonNotifier:          "stat_new_lesson_notifier",
	StatNotifier:                   "stat_notifier",
	Teacher:                        "teacher",
	User:                           "user",
	UserAPIToken:                   "user_api_token",
	UserGoogle:                     "user_google",
}
