FROM golang:1.11.1-alpine AS builder

RUN set -eux \
	&& apk --update add --no-cache \
		bash \
		make

WORKDIR /go/src/github.com/oinume/lekcije
ADD . /go/src/github.com/oinume/lekcije
RUN make install-commands install-dep build/server


FROM alpine
COPY --from=builder /go/src/github.com/oinume/lekcije/bin/lekcije_server /lekcije_server

RUN set -eux \
	&& apk --update add --no-cache ca-certificates

EXPOSE ${PORT:-4001}
EXPOSE ${GRPC_PORT:-4002}

ENTRYPOINT ["/lekcije_server"]
