// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Empty struct {
	ID string `json:"id"`
}

type FollowingTeacher struct {
	ID        string   `json:"id"`
	Teacher   *Teacher `json:"teacher"`
	CreatedAt string   `json:"createdAt"`
}

type Teacher struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
