CREATE DATABASE IF NOT EXISTS lekcije DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES ON lekcije.* TO 'lekcije'@'localhost' IDENTIFIED BY 'lekcije';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES ON lekcije.* TO 'lekcije'@'%' IDENTIFIED BY 'lekcije';
